# Generated by Django 5.0.1 on 2025-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(null=True)),
                ('email', models.TextField(max_length=255)),
                ('senha', models.TextField()),
            ],
        ),
    ]
