# Generated by Django 5.0.1 on 2025-04-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0002_cliente_entrega_itempedido_pedido_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=50)),
                ('permissao', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='transportadora',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('quantidade_estoque', models.IntegerField()),
                ('validade', models.DateField()),
                ('localizacao', models.CharField(max_length=100)),
                ('preco_custo', models.IntegerField()),
                ('preco_venda', models.IntegerField()),
                ('fornecedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('data_movimentacao', models.DateField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.clientes')),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.produtos')),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Entrega',
        ),
        migrations.DeleteModel(
            name='Transportadora',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
