# Generated by Django 5.0.1 on 2025-04-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0003_clientes_fornecedores_usuarios_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='movimentacoes',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='movimentacoes',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='movimentacoes',
            old_name='usuarios_id',
            new_name='usuarios',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='fornecedor_id',
            new_name='fornecedor',
        ),
    ]
