# Generated by Django 5.0.1 on 2025-04-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0004_rename_usuario_id_historico_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacoes',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
