# Generated by Django 5.0.1 on 2025-04-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0005_rename_usuarios_movimentacoes_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
