# Generated by Django 5.0.1 on 2025-05-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0006_alter_clientes_cnpj_alter_clientes_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('operacao', models.CharField(max_length=20)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('data_emissao', models.DateField()),
                ('remetente', models.CharField(blank=True, max_length=100, null=True)),
                ('deposito', models.CharField(max_length=100)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_projeto_TCC.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projeto_TCC.produtos')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_projeto_TCC.notafiscal')),
            ],
        ),
    ]
