# Generated by Django 5.0.1 on 2025-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0007_notafiscal_itemnotafiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
