# Generated by Django 5.0.1 on 2025-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0008_alter_produtos_codigo_alter_produtos_preco_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='operacao',
            field=models.CharField(choices=[('Perda_Estrago', 'Perda/Estrago'), ('Transf.Emprestimo', 'Transf.Empréstimo'), ('Transf.Retorno', 'Transf.Retorno'), ('Transferencia', 'Transferência'), ('Venda_Atacado', 'Venda Atacado'), ('Venda_Varejo', 'Venda Varejo')], max_length=20),
        ),
    ]
