# Generated by Django 5.0.1 on 2025-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0009_alter_notafiscal_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Pendente', 'Pendente')], default='Ativo', max_length=20),
        ),
    ]
