# Generated by Django 5.0.1 on 2025-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0010_alter_notafiscal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='unidade_medida',
            field=models.CharField(choices=[('KG', 'KG'), ('Unidade', 'Unidade')], default='Unidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Cancelado', 'Cancelado'), ('Pendente', 'Pendente')], default='Ativo', max_length=20),
        ),
    ]
