# Generated by Django 5.0.1 on 2025-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0011_produtos_unidade_medida_alter_clientes_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='unidade_medida',
            field=models.CharField(choices=[('Unidade', 'Unidade'), ('Kg', 'Kg')], default='Unidade', max_length=20),
        ),
    ]
