# Generated by Django 5.0.1 on 2025-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0012_alter_produtos_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
