# Generated by Django 5.0.1 on 2025-05-14 16:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0014_alter_clientes_cnpj_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='validade',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
