# Generated by Django 5.0.1 on 2025-05-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_TCC', '0015_alter_produtos_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='validade',
            field=models.DateField(),
        ),
    ]
